# Generated by Django 5.2.6 on 2025-10-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploads',
            name='video_duration',
        ),
    ]
