# Generated by Django 5.2.6 on 2025-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_subscription_subscribed_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_description',
            field=models.TextField(blank=True, default='This user has no description yet.'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_picture',
            field=models.ImageField(blank=True, default='channel_pictures/logo.png', null=True, upload_to='channel_pictures'),
        ),
    ]
