# Generated by Django 5.2.6 on 2025-10-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_channel_channel_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
