# Generated by Django 5.2.6 on 2025-10-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_description',
            field=models.TextField(default='No channel description yet.'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_picture',
            field=models.ImageField(upload_to='channel_pictures/'),
        ),
        migrations.AlterField(
            model_name='useruploads',
            name='video_thumbnail',
            field=models.ImageField(upload_to='upload_thumbnail/'),
        ),
        migrations.AlterField(
            model_name='useruploads',
            name='video_videofile',
            field=models.FileField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='useruploads',
            name='video_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
