# Generated by Django 5.2.6 on 2025-10-07 11:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservideoshistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='uservideoshistory',
            unique_together={('user', 'videos')},
        ),
    ]
