# Generated by Django 5.2.6 on 2025-10-07 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_uservideoshistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservideoshistory',
            old_name='videos',
            new_name='video',
        ),
        migrations.AlterUniqueTogether(
            name='uservideoshistory',
            unique_together={('user', 'video')},
        ),
        migrations.AlterField(
            model_name='uservideoshistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
