# Generated by Django 5.2.6 on 2025-10-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_videos_uservideoshistory_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploads',
            name='video_category',
        ),
    ]
